apiVersion: v1
kind: Namespace
metadata:
  name: prombench-{{ .PR_NUMBER }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgen-scaler
  namespace: prombench-{{ .PR_NUMBER }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loadgen-scaler
  namespace: prombench-{{ .PR_NUMBER }}
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs: ["get", "update"]
---
#need to give update access to loadgen-scaler
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadgen-scaler
  namespace: prombench-{{ .PR_NUMBER }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loadgen-scaler
subjects:
- kind: ServiceAccount
  name: loadgen-scaler
  namespace: prombench-{{ .PR_NUMBER }}
---
#Prometheus RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: prombench-{{ .PR_NUMBER }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-{{ .PR_NUMBER }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: prombench-{{ .PR_NUMBER }}