apiVersion: v1
data:
  prometheus-datasource.yaml: |
    apiVersion: 1

    deleteDatasources:
      - name: Prometheus-prombench-{{ .PR_NUMBER }}
        orgId: 1

    datasources:
    - name: Prometheus-prombench-{{ .PR_NUMBER }}
      type: prometheus
      access: proxy
      orgId: 1
      url: http://{{.INGRESS_IP}}/prombench-{{ .PR_NUMBER }}/prometheus-meta/
      basicAuth: true
      basicAuthUser: admin
      basicAuthPassword: admin
      isDefault: true
      jsonData:
         graphiteVersion: "1.1"
         tlsAuth: false
         tlsAuthWithCACert: false
      secureJsonData:
        tlsCACert: "..."
        tlsClientCert: "..."
        tlsClientKey: "..."
      version: 1
      editable: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-datasources
  namespace: prombench-{{ .PR_NUMBER }}
